enum Permission{
  CAN_GRANT_PERMS, 
  CAN_ASSIGN_TASK, CAN_ASSIGN_ROLE,
  CAN_ADD_MEMBER, CAN_REMOVE_MEMBER,
  CAN_CREATE_TEAM, CAN_EDIT_TEAM, CAN_DISSOLVE_TEAM,
  CAN_CREATE_EVENT, CAN_EDIT_EVENT, CAN_REMOVE_EVENT,
  CAN_CREATE_ROADMAP, CAN_EDIT_ROADMAP, CAN_DELETE_ROADMAP,
  CAN_DELETE_PROJECT, CAN_CREATE_PROJECT, CAN_EDIT_PROJECT, CAN_ASSIGN_PROJECT, 
}